/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_changba_songstudio_video_player_ProjectorPlayer */

#ifndef _Included_com_changba_songstudio_video_player_ProjectorPlayer
#define _Included_com_changba_songstudio_video_player_ProjectorPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    onSurfaceCreated
 * Signature: (Landroid/view/Surface;II)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_onSurfaceCreated
  (JNIEnv *env, jobject obj, jobject surface, jint width, jint height);

/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    onSurfaceDestroyed
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_onSurfaceDestroyed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    prepare
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_prepare
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_play
  (JNIEnv *, jobject);

/*
 * Class:     com_changba_songstudio_video_player_ProjectorPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_changba_songstudio_video_player_ProjectorPlayer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
